version: '3.7'

services:
  rating_client:
    platform: linux/x86_64
    container_name: rating_client
    image: ghcr.io/vmatyagin/rating_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3000'
